#!/bin/bash

set -e

echo "[TRAVIS_SETUP] Preparing build tools..."

# prepare linux env
if [ ${TRAVIS_OS_NAME} = "linux" ]; then
    (sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test) &> 1
    (sudo apt-get update -qq) &> 1
    (sudo apt-get install -y lcov) &> 1
    if [ ${CXX} = "g++" ]; then
        (sudo apt-get install -y gcc-4.8 g++-4.8) &> 1
    fi
    (sudo apt-get install -y graphviz doxygen) &> 1
fi

# prepare mac env
if [ ${TRAVIS_OS_NAME} = "osx" ]; then
    (brew install lcov) &> 1
    (brew install graphviz) &> 1
    (brew install doxygen) &> 1
fi

# use CMake 3.2
echo "[TRAVIS_SETUP] Installing CMake 3.2..."
cd /tmp
(curl http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz | tar -xzf -) &> 1
cd cmake-3.2.2
(./bootstrap && sudo make install -j8) &> 1
