#!/bin/bash

set -e

echo "[TRAVIS_SETUP] Preparing build tools..."

# prepare linux env
if [ ${TRAVIS_OS_NAME} = "linux" ]; then
    (sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test)
    (sudo apt-get update -qq)
    (sudo apt-get install -y lcov)
    if [ ${CXX} = "g++" ]; then
        (sudo apt-get install -y gcc-4.8 g++-4.8)
    fi
    (sudo apt-get install -y graphviz doxygen)
fi

# prepare mac env
if [ ${TRAVIS_OS_NAME} = "osx" ]; then
    (brew install lcov)
    (brew install graphviz)
    (brew install doxygen)
fi

# use CMake 3.2
echo "[TRAVIS_SETUP] Installing CMake 3.2..."
cd /tmp
(curl http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz | tar -xzf -)
cd cmake-3.2.2
(./bootstrap && sudo make install -j8)
