#!/bin/bash

projname=$(basename $(cd "$(dirname "$0")"; pwd))
artname="${projname}_${BTYPE}_${TRAVIS_OS_NAME}_${CC}"

if [ ${TRAVIS_OS_NAME} = "linux" ]; then
    sudo apt-get install uuencode mail
fi

tar -czf - install/* | uuencode "$artname.tar.gz" | mail -s "$artname" akalsi.work@gmail.com <<< "$artname"
